name: CI
on: [push, pull_request]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed
      - name: Clean
        uses: borales/actions-yarn@v4
        with:
          cmd: clean
      - name: Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Format
        uses: borales/actions-yarn@v4
        with:
          cmd: format
      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: test # will run `yarn test` command